"""Decision metadata for every local dashboard API route."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

RouteMethod = Literal["GET", "POST"]
RouteWorkload = Literal["interactive", "bounded_report", "heavy_analysis"]


@dataclass(frozen=True)
class DashboardRouteProfile:
    """Describe the execution and persistence behavior of one API route."""

    method: RouteMethod
    path: str
    handler: str
    owner: str
    workload: RouteWorkload
    scope_behavior: str
    result_bound: str
    cache_behavior: str
    may_scan_all_history: bool


def _profile(
    method: RouteMethod,
    path: str,
    handler: str,
    owner: str,
    workload: RouteWorkload,
    scope_behavior: str,
    result_bound: str,
    cache_behavior: str,
    *,
    may_scan_all_history: bool = False,
) -> DashboardRouteProfile:
    return DashboardRouteProfile(
        method=method,
        path=path,
        handler=handler,
        owner=owner,
        workload=workload,
        scope_behavior=scope_behavior,
        result_bound=result_bound,
        cache_behavior=cache_behavior,
        may_scan_all_history=may_scan_all_history,
    )


_PERSISTED_SNAPSHOT_ROUTES = (
    "overview",
    "tool-output",
    "commands",
    "git-interactions",
    "file-reads",
    "file-modifications",
    "read-productivity",
    "concentration",
    "guided-summary",
)

_PERSISTED_SNAPSHOT_PROFILES = tuple(
    _profile(
        "GET",
        f"/api/diagnostics/{name}",
        f"_handle_diagnostics_{name.replace('-', '_')}",
        "server.diagnostic_snapshots",
        "interactive",
        "Reads one previously computed diagnostic snapshot.",
        "One fixed snapshot payload.",
        "Persisted in SQLite and reused until explicitly refreshed.",
    )
    for name in _PERSISTED_SNAPSHOT_ROUTES
)

_SNAPSHOT_REFRESH_PROFILES = tuple(
    _profile(
        "POST",
        f"/api/diagnostics/{name}/refresh",
        f"_handle_diagnostics_{name.replace('-', '_')}_refresh",
        "server.diagnostic_snapshots",
        "heavy_analysis",
        "Recomputes the named diagnostic over the requested history scope.",
        "One persisted snapshot payload.",
        "Refresh lock serializes work; result is persisted in SQLite.",
        may_scan_all_history=True,
    )
    for name in _PERSISTED_SNAPSHOT_ROUTES
)


DASHBOARD_ROUTE_PROFILES: tuple[DashboardRouteProfile, ...] = (
    _profile(
        "GET",
        "/api/context",
        "_handle_context",
        "server.context",
        "interactive",
        "Reads context for one explicitly selected usage record.",
        "Configured character window.",
        "On-demand source read; not cached.",
    ),
    _profile(
        "GET",
        "/api/context-settings",
        "_handle_context_settings",
        "server.context_settings",
        "interactive",
        "Reads in-memory server settings.",
        "One compact settings payload.",
        "In-memory state for the server lifetime.",
    ),
    _profile(
        "GET",
        "/api/open-investigator",
        "_handle_open_investigator",
        "server.open_investigator",
        "interactive",
        "Targets one investigator URL.",
        "One action payload.",
        "No persisted result.",
    ),
    _profile(
        "GET",
        "/api/status",
        "_handle_status",
        "server.status",
        "interactive",
        "Reads aggregate refresh metadata.",
        "One compact status payload.",
        "Backed by persisted SQLite metadata.",
    ),
    _profile(
        "GET",
        "/api/calls",
        "_handle_calls",
        "server.call_lists",
        "bounded_report",
        "Queries a page; derived filters can require a full matching-row pass.",
        "Default 100 rows with explicit pagination.",
        "Live SQLite query; no response cache.",
        may_scan_all_history=True,
    ),
    _profile(
        "GET",
        "/api/call",
        "_handle_call",
        "server.call_detail",
        "interactive",
        "Reads one selected call and bounded adjacent context.",
        "One call detail payload.",
        "Live SQLite query; no response cache.",
    ),
    _profile(
        "GET",
        "/api/threads",
        "_handle_threads",
        "server.threads",
        "bounded_report",
        "Queries aggregate thread rows over the selected history scope.",
        "Default 100 rows with pagination.",
        "Live SQLite aggregate query.",
        may_scan_all_history=True,
    ),
    _profile(
        "GET",
        "/api/thread-calls",
        "_handle_thread_calls",
        "server.call_lists",
        "bounded_report",
        "Queries one thread; derived filters can load the full thread.",
        "Default 100 rows with pagination.",
        "Live SQLite query; no response cache.",
        may_scan_all_history=True,
    ),
    _profile(
        "GET",
        "/api/summary",
        "_handle_summary",
        "server.summary",
        "bounded_report",
        "Aggregates all matching rows into bounded groups.",
        "Default 20 groups.",
        "Live SQLite/report query; no response cache.",
        may_scan_all_history=True,
    ),
    _profile(
        "GET",
        "/api/recommendations",
        "_handle_recommendations",
        "server.recommendations",
        "heavy_analysis",
        "Loads and ranks all matching calls before applying the result limit.",
        "Default 20 ranked rows.",
        "Recomputed per request; no persisted facts yet.",
        may_scan_all_history=True,
    ),
    _profile(
        "GET",
        "/api/allowance/history",
        "_handle_allowance_history",
        "server.allowance",
        "bounded_report",
        "Normalizes allowance observations over the selected scope.",
        "Default 1,000 observations.",
        "Live SQLite plus local configuration.",
        may_scan_all_history=True,
    ),
    _profile(
        "GET",
        "/api/allowance/diagnostics",
        "_handle_allowance_diagnostics",
        "server.allowance",
        "heavy_analysis",
        "Evaluates allowance evidence over the selected history scope.",
        "Default 10,000 observations.",
        "Computed per request from SQLite and config.",
        may_scan_all_history=True,
    ),
    _profile(
        "GET",
        "/api/allowance/export",
        "_handle_allowance_export",
        "server.allowance",
        "bounded_report",
        "Builds a strict local allowance evidence export.",
        "Schema-bounded aggregate export.",
        "Computed from SQLite and local config.",
        may_scan_all_history=True,
    ),
    _profile(
        "GET",
        "/api/reports/pack",
        "_handle_reports_pack",
        "server.reports",
        "bounded_report",
        "Builds bounded report sections; derived filters may scan history.",
        "Default 100 rows and 8 evidence rows.",
        "Computed per request; no response cache.",
        may_scan_all_history=True,
    ),
    _profile(
        "GET",
        "/api/investigations/agentic",
        "_handle_investigation_agentic",
        "server.investigations",
        "heavy_analysis",
        "Runs an aggregate investigation over matching history.",
        "Default 5 evidence rows.",
        "Computed per request; no persisted run cache.",
        may_scan_all_history=True,
    ),
    _profile(
        "GET",
        "/api/investigations/repeated-files",
        "_handle_investigation_repeated_file_rediscovery",
        "server.investigations",
        "heavy_analysis",
        "Ranks repeated file rediscovery over matching history.",
        "Default 20 patterns and 3 samples.",
        "Computed per request.",
        may_scan_all_history=True,
    ),
    _profile(
        "GET",
        "/api/investigations/shell-churn",
        "_handle_investigation_shell_churn",
        "server.investigations",
        "heavy_analysis",
        "Ranks repeated shell command families over matching history.",
        "Default 20 patterns and 3 samples.",
        "Computed per request.",
        may_scan_all_history=True,
    ),
    _profile(
        "GET",
        "/api/investigations/large-low-output",
        "_handle_investigation_large_low_output",
        "server.investigations",
        "heavy_analysis",
        "Ranks high-input, low-output calls over matching history.",
        "Default 20 rows.",
        "Computed per request.",
        may_scan_all_history=True,
    ),
    _profile(
        "GET",
        "/api/investigations/walk",
        "_handle_investigation_walk",
        "server.investigations",
        "heavy_analysis",
        "Walks aggregate diagnostic hypotheses over matching history.",
        "Default 5 evidence rows.",
        "Computed per request.",
        may_scan_all_history=True,
    ),
    _profile(
        "GET",
        "/api/diagnostics/summary",
        "_handle_diagnostics_summary",
        "server.diagnostic_facts",
        "bounded_report",
        "Aggregates persisted diagnostic facts over matching scope.",
        "Default 20 groups.",
        "Live SQLite query over persisted facts.",
        may_scan_all_history=True,
    ),
    _profile(
        "GET",
        "/api/diagnostics/facts",
        "_handle_diagnostics_facts",
        "server.diagnostic_facts",
        "bounded_report",
        "Queries persisted diagnostic facts with filters.",
        "Default 50 facts.",
        "Live SQLite query over persisted facts.",
        may_scan_all_history=True,
    ),
    _profile(
        "GET",
        "/api/diagnostics/fact-calls",
        "_handle_diagnostics_fact_calls",
        "server.diagnostic_facts",
        "heavy_analysis",
        "Resolves supporting calls for selected diagnostic facts.",
        "Request-bounded evidence rows.",
        "Live SQLite query; no response cache.",
        may_scan_all_history=True,
    ),
    _profile(
        "GET",
        "/api/diagnostics/compactions",
        "_handle_diagnostics_facts",
        "server.diagnostic_facts",
        "bounded_report",
        "Queries persisted compaction facts.",
        "Default 50 facts.",
        "Live SQLite query over persisted facts.",
        may_scan_all_history=True,
    ),
    _profile(
        "GET",
        "/api/diagnostics/tools",
        "_handle_diagnostics_facts",
        "server.diagnostic_facts",
        "bounded_report",
        "Queries persisted tool facts.",
        "Default 50 facts.",
        "Live SQLite query over persisted facts.",
        may_scan_all_history=True,
    ),
    *_PERSISTED_SNAPSHOT_PROFILES,
    _profile(
        "GET",
        "/api/diagnostics/usage-drain",
        "_handle_diagnostics_usage_drain",
        "server.diagnostic_snapshots",
        "interactive",
        "Reads the persisted usage-drain snapshot.",
        "One fixed snapshot payload.",
        "Persisted in SQLite and reused until explicitly refreshed.",
    ),
    _profile(
        "GET",
        "/api/usage",
        "_handle_usage",
        "server.usage_refresh",
        "bounded_report",
        "Reads a configured window; refresh=1 may rebuild all source history.",
        "Configured dashboard row limit or explicit all-history request.",
        "Reads SQLite; optional refresh updates the persisted index.",
        may_scan_all_history=True,
    ),
    _profile(
        "GET",
        "/api/refresh/start",
        "_handle_refresh_start",
        "server.usage_refresh",
        "heavy_analysis",
        "Starts an asynchronous source-history refresh.",
        "One job handle.",
        "Persists index changes; job state is in process.",
        may_scan_all_history=True,
    ),
    _profile(
        "GET",
        "/api/refresh/status",
        "_handle_refresh_status",
        "server.usage_refresh",
        "interactive",
        "Reads one asynchronous refresh job.",
        "One compact job status.",
        "In-process registry for the server lifetime.",
    ),
    _profile(
        "POST",
        "/api/diagnostics/refresh",
        "_handle_diagnostics_refresh",
        "server.diagnostic_snapshots",
        "heavy_analysis",
        "Recomputes every diagnostic snapshot over the selected history.",
        "One aggregate refresh result.",
        "Refresh lock serializes and persists snapshots.",
        may_scan_all_history=True,
    ),
    *_SNAPSHOT_REFRESH_PROFILES,
    _profile(
        "POST",
        "/api/diagnostics/usage-drain/refresh",
        "_handle_diagnostics_usage_drain_refresh",
        "server.diagnostic_snapshots",
        "heavy_analysis",
        "Recomputes the usage-drain snapshot over history.",
        "One persisted snapshot payload.",
        "Refresh lock serializes work; result is persisted in SQLite.",
        may_scan_all_history=True,
    ),
)
