"""Decision metadata for the stable HTTP API v2 surface."""

from codex_usage_tracker.server.route_profile import profile

HTTP_V2_ROUTE_PROFILES = (
    profile(
        "GET",
        "/api/v2/status",
        "_handle_http_v2",
        "interfaces.http.v2",
        "interactive",
        "Reads bounded status for the requested active/all-history scope.",
        "One status contract up to 64 KiB.",
        "No response cache; application context owns source freshness.",
        exposure="stable",
        output_limit_bytes=64 * 1024,
    ),
    profile(
        "POST",
        "/api/v2/refresh",
        "_handle_http_v2",
        "interfaces.http.v2",
        "heavy_analysis",
        "Refreshes active or all-history aggregate state under the shared coordinator.",
        "One refresh or generic job contract up to 128 KiB.",
        "Job reuse is keyed by the application refresh coordinator.",
        may_scan_all_history=True,
        execution="async_start",
        exposure="stable",
        input_limit_bytes=4 * 1024,
        output_limit_bytes=128 * 1024,
    ),
    profile(
        "GET",
        "/api/v2/jobs/{job_id}",
        "_handle_http_v2",
        "interfaces.http.v2",
        "interactive",
        "Reads one exact generic job identifier.",
        "One job contract up to 128 KiB when result inclusion is requested.",
        "Reads the process-local application job registry.",
        execution="poll",
        exposure="stable",
        output_limit_bytes=128 * 1024,
    ),
    profile(
        "POST",
        "/api/v2/analyze",
        "_handle_http_v2",
        "interfaces.http.v2",
        "heavy_analysis",
        "Runs one cataloged analysis over an explicit bounded scope.",
        "One analysis or generic job contract up to 512 KiB.",
        "Semantic jobs are reused by source revision and request fingerprint.",
        may_scan_all_history=True,
        execution="async_start",
        exposure="stable",
        input_limit_bytes=32 * 1024,
        output_limit_bytes=512 * 1024,
    ),
    profile(
        "POST",
        "/api/v2/query",
        "_handle_http_v2",
        "interfaces.http.v2",
        "interactive",
        "Runs one allowlisted query with keyset pagination.",
        "At most 200 rows and 256 KiB.",
        "Live indexed SQLite read bound to source revision.",
        may_scan_all_history=True,
        exposure="stable",
        input_limit_bytes=32 * 1024,
        output_limit_bytes=256 * 1024,
    ),
    profile(
        "POST",
        "/api/v2/evidence",
        "_handle_http_v2",
        "interfaces.http.v2",
        "interactive",
        "Reads one exact evidence selector or bounded thread-call page.",
        "At most 200 aggregate evidence records and 128 KiB.",
        "Live indexed SQLite read; no response cache.",
        may_scan_all_history=True,
        exposure="stable",
        input_limit_bytes=16 * 1024,
        output_limit_bytes=128 * 1024,
    ),
    profile(
        "POST",
        "/api/v2/allowance",
        "_handle_http_v2",
        "interfaces.http.v2",
        "heavy_analysis",
        "Runs one bounded allowance operation or starts semantic analysis.",
        "At most 200 evidence rows or one job contract, up to 256 KiB.",
        "Persisted allowance facts plus reusable semantic jobs.",
        may_scan_all_history=True,
        execution="async_start",
        exposure="stable",
        input_limit_bytes=16 * 1024,
        output_limit_bytes=256 * 1024,
    ),
    profile(
        "GET",
        "/api/v2/capabilities",
        "_handle_http_v2",
        "interfaces.http.v2",
        "interactive",
        "Returns immutable allowlists without reading usage content.",
        "One capabilities contract up to 64 KiB.",
        "Process-static application capability metadata.",
        exposure="stable",
        output_limit_bytes=64 * 1024,
    ),
)
