exclude = [
    "**/*__pycache__",
    "**/*egg-info",
    "**/build",
    "**/dist",
    "**/docs",
    "**/tests",
    "**/venv",
]
source_roots = ["src"]
root_module = "ignore"
forbid_circular_dependencies = false
layers_explicit_depends_on = true
