"""Stable CLI and MCP catalogs shared by release-contract tests."""

CANONICAL_PACKAGE_DESCRIPTION = (
    "Local, evidence-backed Codex usage analyst with MCP tools and an Evidence Console."
)

CANONICAL_DATA_POSTURE = (
    "Normal refresh indexes aggregate counters and the existing bounded local "
    "content/event index; aggregate-only commands retain the older posture; "
    "shareable outputs follow existing behavior."
)

FORBIDDEN_DASHBOARD_DEPENDENCIES = {"three", "@types/three"}
FORBIDDEN_CONSTELLATION_PATHS = {
    "frontend/dashboard/src/features/overview/usageConstellationModel.ts",
    "frontend/dashboard/src/features/overview/usageConstellationModel.test.ts",
    "frontend/dashboard/src/visualization/three",
    "tests/playwright/dashboard-constellation.spec.mjs",
}
MAX_INITIAL_DASHBOARD_JS_KIB = 67

CORE_MCP_TOOL_NAMES = (
    "usage_status",
    "usage_refresh",
    "usage_analyze",
    "usage_query",
    "usage_evidence",
    "usage_allowance",
    "usage_job_status",
)

DEVELOPER_MCP_TOOL_NAMES = {
    "usage_dogfood_start",
    "usage_dogfood_status",
    "usage_dogfood_result",
    "usage_visualization_suggest",
    "usage_visualization_render",
}

STABLE_CLI_COMMANDS = {
    "setup",
    "status",
    "doctor",
    "refresh",
    "analyze",
    "query",
    "open",
    "export",
    "config",
    "service",
    "admin",
}

MCP_TOOL_NAMES = {
    "subagent_usage",
    "refresh_usage_index",
    "usage_refresh_start",
    "usage_refresh_status",
    "usage_doctor",
    "usage_summary",
    "usage_query",
    "usage_status",
    "usage_dedupe_diagnostics",
    "usage_calls",
    "usage_call_detail",
    "usage_threads",
    "usage_report_pack",
    "usage_dashboard_recommendations",
    "usage_allowance_history",
    "usage_allowance_diagnostics",
    "usage_allowance_export",
    "usage_allowance_status",
    "usage_allowance_series",
    "usage_allowance_evidence",
    "usage_allowance_analysis",
    "usage_allowance_analysis_status",
    "usage_compression_start",
    "usage_compression_status",
    "usage_compression_profile",
    "usage_compression_candidates",
    "usage_compression_candidate_detail",
    "usage_compression_simulate",
    "usage_recommendations",
    "session_usage",
    "usage_call_context",
    "most_expensive_usage_calls",
    "usage_pricing_coverage",
    "usage_source_coverage",
    "usage_content_search",
    "usage_thread_trace",
    "usage_repetition_scan",
    "usage_command_loop_scan",
    "usage_file_churn_scan",
    "usage_repeated_file_rediscovery",
    "usage_shell_churn",
    "usage_large_low_output_calls",
    "usage_suggest_investigations",
    "usage_investigate",
    "usage_action_brief",
    "usage_dogfood_start",
    "usage_dogfood_status",
    "usage_dogfood_result",
    "usage_test_hypotheses",
    "usage_context_bloat_scan",
    "usage_investigation_walk",
    "usage_local_evidence_export",
    "generate_usage_dashboard",
    "export_usage_csv",
    "init_usage_pricing_config",
    "update_usage_pricing_config",
    "init_usage_allowance_config",
} | {"usage_visualization_suggest", "usage_visualization_render"}

ADVANCED_MCP_TOOL_NAMES = {
    "usage_dedupe_diagnostics",
    "usage_allowance_export",
    "usage_call_context",
    "usage_content_search",
    "usage_thread_trace",
    "usage_local_evidence_export",
    "export_usage_csv",
}

FULL_MCP_TOOL_NAMES = (MCP_TOOL_NAMES - DEVELOPER_MCP_TOOL_NAMES) | set(CORE_MCP_TOOL_NAMES)
ALL_MCP_TOOL_NAMES = MCP_TOOL_NAMES | set(CORE_MCP_TOOL_NAMES)

MCP_PROFILE_TOOL_COUNTS = {
    "core": len(CORE_MCP_TOOL_NAMES),
    "full": len(FULL_MCP_TOOL_NAMES),
    "developer": len(ALL_MCP_TOOL_NAMES),
}

DEPRECATED_MCP_TOOL_NAMES = {
    "subagent_usage",
    "refresh_usage_index",
    "usage_refresh_start",
    "usage_refresh_status",
    "usage_doctor",
    "usage_summary",
    "usage_calls",
    "usage_call_detail",
    "usage_threads",
    "usage_report_pack",
    "usage_dashboard_recommendations",
    "usage_allowance_history",
    "usage_allowance_diagnostics",
    "usage_allowance_status",
    "usage_allowance_series",
    "usage_allowance_evidence",
    "usage_allowance_analysis",
    "usage_allowance_analysis_status",
    "usage_compression_start",
    "usage_compression_status",
    "usage_compression_profile",
    "usage_compression_candidates",
    "usage_compression_candidate_detail",
    "usage_compression_simulate",
    "usage_recommendations",
    "session_usage",
    "most_expensive_usage_calls",
    "usage_pricing_coverage",
    "usage_source_coverage",
    "usage_repetition_scan",
    "usage_command_loop_scan",
    "usage_file_churn_scan",
    "usage_repeated_file_rediscovery",
    "usage_shell_churn",
    "usage_large_low_output_calls",
    "usage_suggest_investigations",
    "usage_investigate",
    "usage_action_brief",
    "usage_test_hypotheses",
    "usage_context_bloat_scan",
    "usage_investigation_walk",
    "generate_usage_dashboard",
    "init_usage_pricing_config",
    "update_usage_pricing_config",
    "init_usage_allowance_config",
}

RELEASE_SCHEMA_IDS = {
    "codex-usage-tracker-action-brief-v1",
    "codex-usage-tracker-agentic-dogfood-v1",
    "codex-usage-tracker-agentic-investigation-v1",
    "codex-usage-tracker-allowance-analysis-v2",
    "codex-usage-tracker-allowance-diagnostics-v1",
    "codex-usage-tracker-allowance-evidence-export-v1",
    "codex-usage-tracker-allowance-evidence-v2",
    "codex-usage-tracker-allowance-history-v1",
    "codex-usage-tracker-allowance-series-v2",
    "codex-usage-tracker-allowance-status-v2",
    "codex-usage-tracker-allowance-v1",
    "codex-usage-tracker-analysis-job-v1",
    "codex-usage-tracker-async-job-status-v1",
    "codex-usage-tracker-call-v1",
    "codex-usage-tracker-calls-v1",
    "codex-usage-tracker-codex-rate-card-v1",
    "codex-usage-tracker-compression-api-v1",
    "codex-usage-tracker-content-search-v1",
    "codex-usage-tracker-context-disabled-v1",
    "codex-usage-tracker-context-settings-v1",
    "codex-usage-tracker-context-v1",
    "codex-usage-tracker-conversational-readiness-v1",
    "codex-usage-tracker-dashboard-target-v1",
    "codex-usage-tracker-dashboard-target-v2",
    "codex-usage-tracker-dashboard-v1",
    "codex-usage-tracker-dedupe-diagnostics-v1",
    "codex-usage-tracker-diagnostic-commands-v1",
    "codex-usage-tracker-diagnostic-concentration-v1",
    "codex-usage-tracker-diagnostic-file-modifications-v1",
    "codex-usage-tracker-diagnostic-file-reads-v1",
    "codex-usage-tracker-diagnostic-git-interactions-v1",
    "codex-usage-tracker-diagnostic-guided-summary-v1",
    "codex-usage-tracker-diagnostic-overview-v1",
    "codex-usage-tracker-diagnostic-read-productivity-v1",
    "codex-usage-tracker-diagnostic-snapshot-refresh-v1",
    "codex-usage-tracker-diagnostic-tool-output-v1",
    "codex-usage-tracker-diagnostic-usage-drain-v1",
    "codex-usage-tracker-diagnostics-v1",
    "codex-usage-tracker-doctor-v1",
    "codex-usage-tracker-export-v1",
    "codex-usage-tracker-health-v1",
    "codex-usage-tracker-home-summary-v1",
    "codex-usage-tracker-hypothesis-test-v1",
    "codex-usage-tracker-init-allowance-v1",
    "codex-usage-tracker-init-pricing-v1",
    "codex-usage-tracker-init-projects-v1",
    "codex-usage-tracker-init-thresholds-v1",
    "codex-usage-tracker-investigation-suggestions-v1",
    "codex-usage-tracker-investigation-walk-v1",
    "codex-usage-tracker-large-low-output-v1",
    "codex-usage-tracker-live-api-v1",
    "codex-usage-tracker-local-evidence-export-v1",
    "codex-usage-tracker-open-dashboard-v1",
    "codex-usage-tracker-open-investigator-v1",
    "codex-usage-tracker-parse-allowance-v1",
    "codex-usage-tracker-pattern-scan-v1",
    "codex-usage-tracker-pin-pricing-v1",
    "codex-usage-tracker-plugin-install-v1",
    "codex-usage-tracker-plugin-uninstall-v1",
    "codex-usage-tracker-plugin-upgrade-v1",
    "codex-usage-tracker-pricing-v2",
    "codex-usage-tracker-pricing-coverage-v1",
    "codex-usage-tracker-query-v1",
    "codex-usage-tracker-react-selected-report-v1",
    "codex-usage-tracker-rebuild-index-v1",
    "codex-usage-tracker-recommendations-v1",
    "codex-usage-tracker-refresh-v1",
    "codex-usage-tracker-refresh-job-v1",
    "codex-usage-tracker-refresh-progress-v1",
    "codex-usage-tracker-repeated-file-rediscovery-v1",
    "codex-usage-tracker-reports-pack-v1",
    "codex-usage-tracker-reset-db-v1",
    "codex-usage-tracker-serve-dashboard-v1",
    "codex-usage-tracker-session-v1",
    "codex-usage-tracker-setup-v1",
    "codex-usage-tracker-shell-churn-v1",
    "codex-usage-tracker-source-coverage-v1",
    "codex-usage-tracker-status-v1",
    "codex-usage-tracker-summary-v1",
    "codex-usage-tracker-support-bundle-v1",
    "codex-usage-tracker-thread-calls-v1",
    "codex-usage-tracker-thread-trace-v1",
    "codex-usage-tracker-threads-v1",
    "codex-usage-tracker-update-pricing-v1",
    "codex-usage-tracker-update-rate-card-v1",
    "codex-usage-tracker-usage-drain-model-v1",
    "codex-usage-tracker-visualization-result-v1",
    "codex-usage-tracker-visualization-suggestions-v1",
    "codex-usage-tracker.accounting-context.v1",
    "codex-usage-tracker.analysis-job.v1",
    "codex-usage-tracker.analysis-result.v1",
    "codex-usage-tracker.analysis.v2",
    "codex-usage-tracker.capabilities.v2",
    "codex-usage-tracker.compression-profile.v1",
    "codex-usage-tracker.database-integrity.v1",
    "codex-usage-tracker.diagnostic-result.v1",
    "codex-usage-tracker.error.v1",
    "codex-usage-tracker.evidence-result.v1",
    "codex-usage-tracker.evidence.v1",
    "codex-usage-tracker.finding.v1",
    "codex-usage-tracker.freshness.v1",
    "codex-usage-tracker.job.v1",
    "codex-usage-tracker.mcp-envelope.v1",
    "codex-usage-tracker.message.v1",
    "codex-usage-tracker.next-action.v1",
    "codex-usage-tracker.query.v2",
    "codex-usage-tracker.recommendation.v1",
    "codex-usage-tracker.refresh.v2",
    "codex-usage-tracker.refresh-result.v1",
    "codex-usage-tracker.release-artifact-manifest.v1",
    "codex-usage-tracker.release-promotion-evidence.v1",
    "codex-usage-tracker.scope.v1",
    "codex-usage-tracker.status.v2",
    "codex-usage-tracker.subagent-usage.v1",
}

RELEASE_022_SCHEMA_IDS = {
    "codex-usage-tracker-dashboard-target-v2",
    "codex-usage-tracker.accounting-context.v1",
    "codex-usage-tracker.analysis-job.v1",
    "codex-usage-tracker.analysis.v2",
    "codex-usage-tracker.evidence-result.v1",
    "codex-usage-tracker.evidence.v1",
    "codex-usage-tracker.finding.v1",
    "codex-usage-tracker.freshness.v1",
    "codex-usage-tracker.mcp-envelope.v1",
    "codex-usage-tracker.message.v1",
    "codex-usage-tracker.next-action.v1",
    "codex-usage-tracker.query.v2",
    "codex-usage-tracker.recommendation.v1",
    "codex-usage-tracker.scope.v1",
}
