import type { ZhHansPattern } from './types';

export const limitsZhHansTranslations: Readonly<Record<string, string>> = {
  'Current limit status': '当前限额状态',
  'Capacity history': '容量历史',
  'Capacity changes': '容量变化',
  'Capacity chart legend': '容量图图例',
  'Subscription plan key': '订阅方案图例',
  'Chart mark key': '图表标记图例',
  'Plan': '方案',
  'Mark': '标记',
  'Observed reset window': '已观测重置窗口',
  'Trailing 8-window median': '最近 8 个窗口中位数',
  'Weekly limit capacity over time': '每周限额容量趋势',
  'Weekly limit capacity': '每周限额容量',
  'Reset-window completion': '重置窗口完成时间',
  'Reset window completed': '重置窗口已完成',
  'Credits / 1%': '点数 / 1%',
  'Subscription plan': '订阅方案',
  'Rolling median': '滚动中位数',
  'Rolling Q1': '滚动第一四分位数',
  'Rolling Q3': '滚动第三四分位数',
  'Quality': '质量',
  'Price coverage': '定价覆盖率',
  'How to read and trust this chart': '如何阅读并判断此图的可信度',
  'Methodology': '方法说明',
  'What each mark means': '各标记的含义',
  'Which evidence counts': '哪些证据计入分析',
  'When a change is called reliable': '何时可将变化视为可靠',
  'Current chart evidence': '当前图表证据',
  'Chart range': '图表范围',
  'Analysis scope': '分析范围',
  'Eligibility filter': '资格筛选',
  'Boundary scan': '边界扫描',
  'Result': '结果',
  'Supported capacity changes': '受支持的容量变化',
  'Eligible reset windows': '符合条件的重置窗口',
  'Last analyzed': '最近分析时间',
  'Analyzing': '正在分析',
  'In progress': '进行中',
  'Not yet': '尚未',
  'Checking capacity history': '正在检查容量历史',
  'More completed reset windows needed': '需要更多已完成的重置窗口',
  'Capacity analysis is queued': '容量分析已排队',
  'No reliable capacity change detected': '未检测到可靠的容量变化',
  'No supported change': '没有受支持的变化',
  'Insufficient evidence': '证据不足',
  'Queued': '已排队',
  'Show full range': '显示完整范围',
  'Use robust range': '使用稳健范围',
  'History range': '历史范围',
  'History range result': '历史范围结果',
  'By reset window': '按重置窗口',
  'Weekly': '每周',
  'Monthly': '每月',
  'Start date': '开始日期',
  'End date': '结束日期',
  'Choose both dates to load the custom range.': '请选择开始和结束日期以加载自定义范围。',
  'Loading capacity history…': '正在加载容量历史…',
  'No completed-cycle capacity history for this range.': '此范围内没有已完成周期的容量历史。',
  'Source evidence': '来源证据',
  'Latest supporting intervals': '最新支撑区间',
  'Newest first. Each page is bounded to 50 canonical local intervals.': '按最新优先显示；每页最多 50 个规范化本地区间。',
  'Latest-first allowance intelligence evidence': '按最新优先的限额分析证据',
  'Observed': '观测时间',
  'Used': '已用',
  'Window': '窗口',
  'Evidence': '证据',
  'Cohort': '分组',
  'Provenance': '来源追踪',
  'Open source call': '打开来源调用',
  'Copy source call link': '复制来源调用链接',
  'Canonical aggregate': '规范化聚合数据',
  'Loading evidence…': '正在加载证据…',
  'No evidence in this page.': '此页没有证据。',
};

export const limitsZhHansPatterns: ReadonlyArray<ZhHansPattern> = [
  { pattern: /^(\d+) supported$/u, replace: '$1 个受支持变化' },
  { pattern: /^(.+) reset-window capacity$/u, replace: '$1 重置窗口容量' },
  { pattern: /^(.+) trailing median$/u, replace: '$1 滚动中位数' },
  { pattern: /^(\d+) reset windows$/u, replace: '$1 个重置窗口' },
  { pattern: /^(\d+) eligible$/u, replace: '$1 个符合条件' },
  { pattern: /^(\d+) excluded$/u, replace: '$1 个已排除' },
  { pattern: /^(\d+) candidates tested$/u, replace: '已测试 $1 个候选边界' },
  { pattern: /^(\d+) supported (change|changes)$/u, replace: '$1 个受支持变化' },
];
