"""Predictive usage-drain model specifications."""

from __future__ import annotations

from codex_usage_tracker.usage_drain.types import PredictiveModelSpec


def predictive_model_specs() -> list[PredictiveModelSpec]:
    base = (
        "standard_usage_credits",
        "log_standard_usage_credits",
    )
    token_shape = (
        *base,
        "row_count",
        "input_tokens",
        "cached_input_tokens",
        "uncached_input_tokens",
        "output_tokens",
        "reasoning_output_tokens",
        "total_tokens",
        "cache_ratio",
        "output_token_share",
        "reasoning_output_share",
        "mean_usage_credits_per_call",
    )
    turn_batching = (
        *token_shape,
        "turn_count",
        "log_turn_count",
        "multi_call_turn_count",
        "max_calls_in_turn",
        "same_turn_share",
        "calls_per_turn",
        "credits_per_turn",
        "tokens_per_turn",
        "input_tokens_per_turn",
        "output_tokens_per_turn",
        "credits_per_call",
        "tokens_per_call",
    )
    fast_proxy = (
        *turn_batching,
        "candidate_standard_credits",
        "non_candidate_standard_credits",
        "candidate_credit_share",
        "documented_fast_weighted_credits",
        "documented_fast_extra_credits",
    )
    effort_controls = (
        *fast_proxy,
        "effort_purity",
        "effort_low_share",
        "effort_medium_share",
        "effort_high_share",
        "effort_xhigh_share",
        "effort_missing_share",
        "effort_other_share",
        "effort_non_xhigh_share",
    )
    online_capacity_controls = (
        *effort_controls,
        "previous_capacity_credits_per_percent",
        "rolling3_capacity_credits_per_percent",
        "rolling10_capacity_credits_per_percent",
        "rolling10_median_capacity_credits_per_percent",
        "ewma_capacity_credits_per_percent",
        "previous_capacity_deltaprediction",
        "rolling3_capacity_deltaprediction",
        "rolling10_capacity_deltaprediction",
        "rolling10_median_capacity_deltaprediction",
        "ewma_capacity_deltaprediction",
        "rolling3_remainder_credits",
        "rolling3_remainder_fraction",
        "rolling3_remainder_floor_deltaprediction",
        "rolling3_remainder_ceiling_deltaprediction",
        "ewma_remainder_credits",
        "ewma_remainder_fraction",
        "ewma_remainder_floor_deltaprediction",
        "ewma_remainder_ceiling_deltaprediction",
    )
    usage_state = (
        *online_capacity_controls,
        "baseline_used_percent",
        "usage_window_minutes",
        "rate_limit_primary_window_minutes",
        "reset_remaining_minutes",
        "window_elapsed_minutes",
        "window_elapsed_fraction",
    )
    time_controls = (
        *usage_state,
        "days_since_first_span",
        "hour_sin",
        "hour_cos",
        "day_of_week_sin",
        "day_of_week_cos",
        "is_weekend",
    )
    duration_controls = (
        *time_controls,
        "call_duration_seconds",
        "mean_call_duration_seconds",
        "previous_call_delta_seconds",
        "span_wall_time_seconds",
        "span_wall_time_minutes",
        "mean_span_wall_time_seconds_per_call",
    )
    lag_regime = (
        *usage_state,
        "previous_delta_percent",
        "previous_drain_per_credit",
        "rolling3_delta_percent",
        "rolling10_delta_percent",
        "rolling50_delta_percent",
        "rolling10_median_delta_percent",
        "rolling10_mode_delta_percent",
        "rolling10_delta_stddev",
        "rolling50_delta_stddev",
        "one_percent_streak",
        "low_delta_streak",
        "same_delta_streak",
        "high_delta_streak",
        "hybrid_streak_delta_percent",
        "rolling3_drain_per_credit",
        "rolling10_drain_per_credit",
        "rolling50_drain_per_credit",
        "rolling10_low_delta_share",
        "rolling3_to_50_delta_ratio",
        "same_bucket_rolling10_delta_percent",
        "same_bucket_rolling10_mode_delta_percent",
        "same_bucket_rolling10_drain_per_credit",
        "same_bucket_seen_count",
        "same_date_rolling10_delta_percent",
        "same_date_rolling10_mode_delta_percent",
        "same_date_seen_count",
        "same_hour_rolling10_delta_percent",
        "same_hour_rolling10_mode_delta_percent",
        "same_hour_seen_count",
        "same_day_of_week_rolling10_delta_percent",
        "same_day_of_week_rolling10_mode_delta_percent",
        "same_day_of_week_seen_count",
        "ewma_delta_percent",
        "ewma_drain_per_credit",
    )
    lag_time = (
        *lag_regime,
        "days_since_first_span",
        "hour_sin",
        "hour_cos",
        "day_of_week_sin",
        "day_of_week_cos",
        "is_weekend",
    )
    adaptive_full = (
        *lag_time,
        "call_duration_seconds",
        "mean_call_duration_seconds",
        "previous_call_delta_seconds",
        "span_wall_time_seconds",
        "span_wall_time_minutes",
        "mean_span_wall_time_seconds_per_call",
    )
    return [
        PredictiveModelSpec("baseline_train_mean", ()),
        PredictiveModelSpec("credits_only", base),
        PredictiveModelSpec("token_shape", token_shape),
        PredictiveModelSpec("turn_batching", turn_batching),
        PredictiveModelSpec("fast_proxy", fast_proxy),
        PredictiveModelSpec(
            "effort_controls",
            effort_controls,
            ("dominant_effort", "effort_mix"),
        ),
        PredictiveModelSpec(
            "online_capacity_controls",
            online_capacity_controls,
            ("dominant_effort", "effort_mix"),
        ),
        PredictiveModelSpec(
            "usage_state",
            usage_state,
            (
                "rate_limit_plan_type",
                "rate_limit_limit_id",
                "usage_window_source",
                "dominant_effort",
                "effort_mix",
            ),
        ),
        PredictiveModelSpec(
            "time_controls",
            time_controls,
            (
                "rate_limit_plan_type",
                "rate_limit_limit_id",
                "usage_window_source",
                "dominant_effort",
                "effort_mix",
                "day_of_week",
            ),
        ),
        PredictiveModelSpec(
            "date_day_hour_controls",
            time_controls,
            (
                "rate_limit_plan_type",
                "rate_limit_limit_id",
                "usage_window_source",
                "dominant_effort",
                "effort_mix",
                "date",
                "day_of_week",
                "hour_bucket",
            ),
        ),
        PredictiveModelSpec(
            "full_controls",
            duration_controls,
            (
                "rate_limit_plan_type",
                "rate_limit_limit_id",
                "usage_window_source",
                "dominant_effort",
                "effort_mix",
                "date",
                "day_of_week",
                "hour_bucket",
            ),
        ),
        PredictiveModelSpec(
            "lag_regime",
            lag_regime,
            (
                "rate_limit_plan_type",
                "rate_limit_limit_id",
                "usage_window_source",
                "dominant_effort",
                "effort_mix",
            ),
        ),
        PredictiveModelSpec(
            "lag_time_controls",
            lag_time,
            (
                "rate_limit_plan_type",
                "rate_limit_limit_id",
                "usage_window_source",
                "dominant_effort",
                "effort_mix",
                "day_of_week",
            ),
        ),
        PredictiveModelSpec(
            "adaptive_full_controls",
            adaptive_full,
            (
                "rate_limit_plan_type",
                "rate_limit_limit_id",
                "usage_window_source",
                "dominant_effort",
                "effort_mix",
                "date",
                "day_of_week",
                "hour_bucket",
            ),
        ),
    ]
